"""Add the eyepiece table

Revision ID: 184a3e3670d9
Revises: c15d98655455
Create Date: 2018-03-09 20:12:20.563889

"""

# revision identifiers, used by Alembic.
revision = '184a3e3670d9'
down_revision = 'c15d98655455'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eyepiece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('fov', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eyepiece')
    ### end Alembic commands ###
