"""Initial Alembic revision

Revision ID: c15d98655455
Revises: None
Create Date: 2018-03-09 19:51:50.440660

"""

# revision identifiers, used by Alembic.
revision = 'c15d98655455'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
